### ISSUE TITLE
KeyError when pointing viewer to .zip

### ISSUE THREAD

**Issue by skylerheise** [hfaran/slack-export-viewer#109]
I keep getting the following error and trace when I try to open the export viewer: Traceback (most recent call last):
  File "/usr/local/bin/slack-export-viewer", line 10, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/slackviewer/main.py", line 61, in main
    configure_app(app, archive, channels, no_sidebar, no_external_references, debug)
  File "/Library/Python/2.7/site-packages/slackviewer/main.py", line 29, in configure_app
    top.mpim_users = reader.compile_mpim_users()
  File "/Library/Python/2.7/site-packages/slackviewer/reader.py", line 107, in compile_mpim_users
    mpim_members = {"name": mpim["name"], "users": [self.__USER_DATA[m] for m in mpim["members"]]}
KeyError: u'U094J8VTL'

the window doesn't open at any point, but the process continues for a while before it crashes.

**Comment by hfaran** [comment]
Can you add a breakpoint on this line and see what __USER_DATA contains? Looks like for some reason that name isn't populated in the dictionary with that ID.

**Comment by skylerheise** [comment]
What do you mean by "add a breakpoint on this line"? I'm assuming I'm not just navigating to the user data directory path.

**Comment by skylerheise** [comment]
A colleague of mine tried it with a new install of the viewer, and ended up getting the same error as I did.

**Comment by anocai** [comment]
Same error as above.

**Comment by jwh1981** [comment]
I am having the same issue. The cause of the KeyError (for us) is that the user in question is not with our organization and an outside consultant. Therefore they are single channel and not in our users.json

The issue then appears to be that, since the mpims.json has an invalid user, the program fails.
