### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Iwifia** [hfaran/slack-export-viewer#122]
```
/mnt/c/Users/name/CentOS7$ slack-export-viewer -z SlackExport.zip --test
/tmp/_slackviewer/26b10a07947e773d8f07e2e3503d54a317f0256f already exists
Traceback (most recent call last):
  File "/home/cdeli/.local/bin/slack-export-viewer", line 11, in <module>
    sys.exit(main())
  File "/home/cdeli/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/cdeli/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/cdeli/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cdeli/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/cdeli/.local/lib/python3.6/site-packages/slackviewer/main.py", line 61, in main
    configure_app(app, archive, channels, no_sidebar, no_external_references, debug)
  File "/home/cdeli/.local/lib/python3.6/site-packages/slackviewer/main.py", line 24, in configure_app
    top.channels = reader.compile_channels(channels)
  File "/home/cdeli/.local/lib/python3.6/site-packages/slackviewer/reader.py", line 35, in compile_channels
    return self._create_messages(channel_names, channel_data)
  File "/home/cdeli/.local/lib/python3.6/site-packages/slackviewer/reader.py", line 176, in _create_messages
    chats = self._build_threads(chats)
  File "/home/cdeli/.local/lib/python3.6/site-packages/slackviewer/reader.py", line 199, in _build_threads
    for reply in message._message['replies']:
KeyError: 'replies'
```

**Comment by hfaran** [comment]
Duplicate of #121
