### ISSUE TITLE
Running slack-export-viewer returns errors

### ISSUE THREAD

**Issue by nvitiritti** [hfaran/slack-export-viewer#128]
* Serving Flask app "slackviewer.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [15/May/2020 11:04:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/May/2020 11:04:39] "[35m[1mGET / HTTP/1.1[0m" 500 -
Error on request:
Traceback (most recent call last):
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\app.py", line 91, in index
    return channel_name("general")
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\app.py", line 19, in channel_name
    return flask.render_template("viewer.html", messages=messages,
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\templates\viewer.html", line 64, in top-level template code
    {{render_message(message, None, no_external_references)}}
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\jinja2\runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\templates\util.html", line 22, in template
    {%if message.user.email%} <span class="print-only user-email">({{message.user.email}})</span>{%endif%}
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\message.py", line 31, in user
    return self._formatter.find_user(self._message)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\formatter.py", line 32, in find_user
    if message.get("subtype", "").startswith("bot_") and message["bot_id"] not in self.__USER_DATA:
KeyError: 'bot_id'
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\werkzeug\serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\app.py", line 91, in index
    return channel_name("general")
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\app.py", line 19, in channel_name
    return flask.render_template("viewer.html", messages=messages,
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\templates\viewer.html", line 64, in top-level template code
    {{render_message(message, None, no_external_references)}}
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\jinja2\runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\templates\util.html", line 22, in template
    {%if message.user.email%} <span class="print-only user-email">({{message.user.email}})</span>{%endif%}
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\message.py", line 31, in user
    return self._formatter.find_user(self._message)
  File "C:\Users\n561541\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\slackviewer\formatter.py", line 32, in find_user
    if message.get("subtype", "").startswith("bot_") and message["bot_id"] not in self.__USER_DATA:
KeyError: 'bot_id'

Additionally when the browser starts I receive a internal server error.

**Comment by NernTheStrudel** [comment]
Also getting this error.
