### ISSUE TITLE
NoneType error

### ISSUE THREAD

**Issue by csaket** [hfaran/slack-export-viewer#159]
Running into an issue with archive that used to work.
viewer displays error and exists.
```
❯ slack-export-viewer -z ./slack 
Archive already extracted. Viewing from ~/slackexport/slack...
Traceback (most recent call last):
  File "~/.pyenv/versions/3.10.2/bin/slack-export-viewer", line 33, in <module>
    sys.exit(load_entry_point('slack-export-viewer==1.1.4', 'console_scripts', 'slack-export-viewer')())
  File "~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/slackviewer/main.py", line 61, in main
    configure_app(app, archive, channels, no_sidebar, no_external_references, debug)
  File "~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/slackviewer/main.py", line 24, in configure_app
    top.channels = reader.compile_channels(channels)
  File "~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/slackviewer/reader.py", line 45, in compile_channels
    channel_data = self._read_from_json("channels.json")
  File "~/.pyenv/versions/3.10.2/lib/python3.10/site-packages/slackviewer/reader.py", line 279, in _read_from_json
    return {u["id"]: u for u in json.load(f)}
TypeError: 'NoneType' object is not iterable
```

No further output whether debug is used or not.
Tested on windows and wsl/linux

**Comment by csaket** [comment]
closing as this seems to be a bug with slackdump
