### ISSUE TITLE
Viewer will not open

### ISSUE THREAD

**Issue by symone7** [hfaran/slack-export-viewer#194]
Traceback (most recent call last):
File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__return self.main(*args, **kwargs)
File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in __main__rv = self.invoke(ctx)
File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in __invoke_return ctx.invoke(self.callback, **ctx.params)
File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 738, in __invoke_return __callback(*args, **kwargs)
File "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 77, in main raise ValueError(“Empty path provided for archive)
ValueError: Empty path provided for archive

**Comment by volker-fr** [comment]
You need to provided the `-z <older` or `-z file.zip` flag:

```
slack-export-viewer -z my-export.zip
```
