### ISSUE TITLE
Error on request?

### ISSUE THREAD

**Issue by andrewthecoder** [hfaran/slack-export-viewer#20]
Hi, when I try to run slack-export-viewer I get the following error:

```
root@dev:/var/home/abeveridge/slack-history# slack-export-viewer -p 54321 -z slack-export-26.04.2016-14.47.zip
slack-export-26.04.2016-14.47.zip extracting to /tmp/_slackviewer/ffcc65ff4a2926970c0e5c95d9acdd973019e106...
slack-export-26.04.2016-14.47.zip extracted to /tmp/_slackviewer/ffcc65ff4a2926970c0e5c95d9acdd973019e106.
 * Running on http://localhost:54321/ (Press CTRL+C to quit)
127.0.0.1 - - [26/Apr/2016 15:11:11] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/slackviewer/app.py", line 24, in index
    return channel_name("general")
  File "/usr/local/lib/python2.7/dist-packages/slackviewer/app.py", line 17, in channel_name
    channels=sorted(channels))
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/slackviewer/templates/viewer.html", line 34, in top-level template code
    <div class="msg">{{ message.msg|safe }}</div>
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
  File "/usr/local/lib/python2.7/dist-packages/slackviewer/message.py", line 52, in msg
    text = self._render_text(text)
  File "/usr/local/lib/python2.7/dist-packages/slackviewer/message.py", line 105, in _render_text
    message = re.sub(r"<#C0\w+>", self._sub_channel_ref, message)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/local/lib/python2.7/dist-packages/slackviewer/message.py", line 183, in _sub_channel_ref
    channel_name = self.__CHANNEL_DATA[channel_id]["name"]
KeyError: u'C0VGDB8P4'
```

Any suggestions?

Thanks!

**Comment by hfaran** [comment]
Ooh, this looks like a case I haven't encountered before. Would you be able to provide me with the archive you were trying to open so I can debug? I absolutely understand if there's sensitive data, in which case just the channels.json file from the archive would help.

As a workaround in the meantime, you could wrap that line as follows for now:

```python
try:
     channel_name = self.__CHANNEL_DATA[channel_id]["name"]
except KeyError:
    channel_name = None
```

**Comment by hfaran** [comment]
I'll actually push a fix tomorrow with the above patch, but I'd still like to understand why that specific channel name isn't in `__CHANNEL_DATA`, because it really **should** be.

**Comment by andrewthecoder** [comment]
I've emailed you my channels.json. Thanks!

**Comment by hfaran** [comment]
Yeah so looking in your channels.json, it appears information for that channel isn't available which is quite odd. I've pushed a fix for now to an other branch which will basically just set the channel name to its ID because there's no other data available.

Can you try installing the version on the branch with:
```
pip install -e git://github.com/hfaran/slack-export-viewer.git@hfaran_nochannelref#egg=slack-export-viewer
```
and tell me if it works?

**Comment by andrewthecoder** [comment]
It does indeed! Thanks a bunch.

**Comment by hfaran** [comment]
Lovely. I've just pushed version `0.1.6` to PyPI with this fix. You can install with `pip install slack-export-viewer -U` now if you wish.

**Comment by ottominggu** [comment]
C:\>slack-export-viewer -z f:/Slackchat/hita.zip
/tmp\_slackviewer\2eb3aac8e2200c59495898f693f1a2752d946d34 already exists
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
ERROR:root:A channel reference was detected but metadata not found in channels.json: u'C0AK0LRFX'
ERROR:root:A channel reference was detected but metadata not found in channels.json: u'C0AK0LRFX'
ERROR:root:A channel reference was detected but metadata not found in channels.json: u'C0AMH9V26'
ERROR:root:A channel reference was detected but metadata not found in channels.json: u'C0AMH9V26'
ERROR:root:A channel reference was detected but metadata not found in channels.json: u'C0BS45DBJ'
ERROR:root:A channel reference was detected but metadata not found in channels.json: u'C0BS45DBJ'
127.0.0.1 - - [30/Apr/2016 13:10:50] "GET / HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Apr/2016 13:10:50] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\werkzeug\serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "c:\python27\lib\site-packages\werkzeug\serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "c:\python27\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\python27\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "c:\python27\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\slackviewer\app.py", line 24, in index
    return channel_name("general")
  File "c:\python27\lib\site-packages\slackviewer\app.py", line 17, in channel_name
    channels=sorted(channels))
  File "c:\python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "c:\python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\slackviewer\templates\viewer.html", line 34, in top-level template code
    <div class="msg">{{ message.msg|safe }}</div>
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 408, in getattr
    return getattr(obj, attribute)
  File "c:\python27\lib\site-packages\slackviewer\message.py", line 71, in msg
    if not message[0].strip():
IndexError: list index out of range
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\werkzeug\serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "c:\python27\lib\site-packages\werkzeug\serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "c:\python27\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\python27\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "c:\python27\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\slackviewer\app.py", line 24, in index
    return channel_name("general")
  File "c:\python27\lib\site-packages\slackviewer\app.py", line 17, in channel_name
    channels=sorted(channels))
  File "c:\python27\lib\site-packages\flask\templating.py", line 128, in render_template
    context, ctx.app)
  File "c:\python27\lib\site-packages\flask\templating.py", line 110, in _render
    rv = template.render(context)
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\slackviewer\templates\viewer.html", line 34, in top-level template code
    <div class="msg">{{ message.msg|safe }}</div>
  File "c:\python27\lib\site-packages\jinja2\environment.py", line 408, in getattr
    return getattr(obj, attribute)
  File "c:\python27\lib\site-packages\slackviewer\message.py", line 71, in msg
    if not message[0].strip():
IndexError: list index out of range

**Comment by ottominggu** [comment]
Any suggestions? already upgrade with latest version

Thanks

**Comment by hfaran** [comment]
@ottominggu Thanks for the report; I'll open a new issue for this.

**Comment by hfaran** [comment]
Opened #22 to follow up with your issue
