### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by gazialankus** [hfaran/slack-export-viewer#26]
[EDITED] 
We have a Slack team with a unicode character in its name. We get the following error. Changing the name of the slack archive fixes it.

```
C:\SomeFolder> slack-export-viewer -z "archive_name_with_the_chacarcetr_ç.zip"
Traceback (most recent call last):
  File "c:\development\secondlife\python278\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\development\secondlife\python278\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Development\SecondLife\Python278\Scripts\slack-export-viewer.exe\__main__.py", line 9, in <module>
  File "c:\development\secondlife\python278\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\development\secondlife\python278\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\development\secondlife\python278\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\development\secondlife\python278\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\development\secondlife\python278\lib\site-packages\slackviewer\main.py", line 60, in main
    configure_app(app, archive, debug)
  File "c:\development\secondlife\python278\lib\site-packages\slackviewer\main.py", line 34, in configure_app
    path = extract_archive(archive)
  File "c:\development\secondlife\python278\lib\site-packages\slackviewer\archive.py", line 59, in extract_archive
    extracted_path))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc7' in position 12: ordinal not in range(128)
```

**Comment by hfaran** [comment]
From first glance it looks the filename which you have actually redacted contains Unicode characters which is what is causing the issue here. You might want to unredact it if you'd like me to fix this. 😛

**Comment by hfaran** [comment]
Oh never mind, I just saw your edit. A cedilla I see.
The fix should be a simple `.encode('utf-8')` on the string. You're welcome to try it out and see if that fixes it then submit a PR. 😄

**Comment by hfaran** [comment]
Another potential fix you can try is what I did here: https://github.com/hfaran/slack-export-viewer/commit/de4f8595b5a7d4984ce0375dd38a3c91f829949c#diff-54c9835624412f076ed121e96671e26bR1

**Comment by hfaran** [comment]
Should be resolved with https://github.com/hfaran/slack-export-viewer/commit/ac4eafbd51d54c7f7379500441e38cd7f328c1bb
