### ISSUE TITLE
A demo or an Example

### ISSUE THREAD

**Issue by TangSteven** [hfaran/slack-export-viewer#37]
It would be a great benefit if an example of the html output was in this repository. I can't seem to try it until #34 is fixed. Also, I would like contribute by improving the css, if the screenshot is accurate.

**Comment by hfaran** [comment]
If you have an example dataset you'd like to volunteer to add as an example, that would be fantastic.
And yep, I'll try to get #34 fixed, but I need a json file with the offending characters to reproduce the issue.

**Comment by SpitUnicsoft** [comment]
Hi @hfaran! 
Thank you for your great job! 
Please take a look at the file attached (hf.zip). It produces next error on Windows 10 x64:
C:\XX>slack-export-viewer -z hf.zip
/tmp\_slackviewer\1e1584694b283d5f2c098dec43343d00426c2536 already exists
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python36-32\Scripts\slack-export-viewer.EXE\__main__.py", line 9, in <module>
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files (x86)\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\slackviewer\main.py", line 60, in main
    configure_app(app, archive, debug)
  File "c:\program files (x86)\python36-32\lib\site-packages\slackviewer\main.py", line 37, in configure_app
    channels = compile_channels(path, user_data, channel_data)
  File "c:\program files (x86)\python36-32\lib\site-packages\slackviewer\archive.py", line 24, in compile_channels
    day_messages = json.load(f)
  File "c:\program files (x86)\python36-32\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "c:\program files (x86)\python36-32\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 129: character maps to <undefined>
[hf.zip](https://github.com/hfaran/slack-export-viewer/files/1098480/hf.zip)

I appreciate you fixing the bug.
