### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by accuratefeed** [hfaran/slack-export-viewer#63]
I saw #24 and I thought this issue was fixed.  I'm getting the following error:

`PS C:\Users\AccurateFeed\downloads> slack-export-viewer --archive ldrs.zip
ldrs.zip extracting to C:\Users\AccurateFeed\AppData\Local\Temp\2\_slackviewer\5e226d974f1b15de666dab44c8ea52f329d39587...
ldrs.zip extracted to C:\Users\AccurateFeed\AppData\Local\Temp\2\_slackviewer\5e226d974f1b15de666dab44c8ea52f329d39587.
 * Serving Flask app "slackviewer.app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [02/May/2018 09:10:57] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\werkzeug\serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\werkzeug\serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2309, in __call__    return self.wsgi_app(environ, start_response)
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2295, in wsgi_app    response = self.handle_exception(e)
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app    response = self.full_dispatch_request()
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\AccurateFeed\appdata\local\programs\python\python36-32\lib\site-packages\slackviewer\app.py", line 81, in index
    return channel_name(channels[0])
IndexError: list index out of range`

**Comment by tscritch** [comment]
Hey @accuratefeed can you add your channels.json file or a snippet of it. The only reason I can see this happening is because there are no channels at all. But if that's not the case I can test with your data. 
Thanks!

**Comment by accuratefeed** [comment]
Hi @tscritch thanks for replying so quickly.  The channels.json file is indeed empty.  I contacted slack about this and they're not sure why it's empty either.  I do have the folder of the channel I'm trying to view though and the other json files such as users.json has data in it.  I'm really just trying to put this 1 channel in a viewable format, so if you have any other suggestions, please let me know!

**Comment by tscritch** [comment]
Wow. Interesting! haha 
Well the list of channels is created from that channels.json so we need it... I would suggest for now just manually creating the file. Go to the tests folder in this project and open the zip to find the channels.json and just copy one from there. I'm not sure what else you could do if you don't have data in that file.

**Comment by accuratefeed** [comment]
@tscritch I was able to find a channels.json with data in it.  Now I'm getting the following error:

> PS C:\Users\jukou\downloads> slack-export-viewer --archive ldrs.zip
ldrs.zip extracting to C:\Users\jukou\AppData\Local\Temp\2\_slackviewer\25cc1dfe34b348f9bc8e83888e92fcff8f708853...
ldrs.zip extracted to C:\Users\jukou\AppData\Local\Temp\2\_slackviewer\25cc1dfe34b348f9bc8e83888e92fcff8f708853.
Traceback (most recent call last):
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jukou\AppData\Local\Programs\Python\Python36-32\Scripts\slack-export-viewer.exe\__main__.py", line 9, in <module>
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\site-packages\slackviewer\main.py", line 76, in main
    configure_app(app, archive, debug)
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\site-packages\slackviewer\main.py", line 41, in configure_app
    groups = compile_groups(path, user_data, group_data)
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\site-packages\slackviewer\archive.py", line 67, in compile_groups
    day_messages = json.load(f)
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "c:\users\jukou\appdata\local\programs\python\python36-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 428: character maps to <undefined>

**Comment by tscritch** [comment]
Ah jeez haha it looks like that would be a character it can't read for some reason... I'm not too experienced with that stuff. @hfaran any insight?

**Comment by tscritch** [comment]
Ok great. 
It is using utf8 👍

**Comment by hfaran** [comment]
@tscritch Looking at the stack trace that @accuratefeed posted, the bug is here: https://github.com/hfaran/slack-export-viewer/blob/5d9608d3945aa822bced0139477c811c4f8c9ab9/slackviewer/reader.py#L145-L147

![image](https://user-images.githubusercontent.com/2450496/39658863-054d5fd4-4fd1-11e8-81b7-9b497f2f4f82.png)

You're missing the `encoding="utf8"` argument on io.open

**Comment by hfaran** [comment]
Committed the fix, but I'm gonna wait until your next PR goes to make a new release

**Comment by hfaran** [comment]
Actually, I went ahead and released 0.6.0. @accuratefeed please try it
