### ISSUE TITLE
extracted archives not working

### ISSUE THREAD

**Issue by Mikeldiazot** [hfaran/slack-export-viewer#71]
Hi @tscritch,
I can´t view the zip file after following instructions.
Here is the log:

MacBook-Air-de-Mikel:documents mikel$ slack-export-viewer -z slack162018.zip
slack162018.zip extracting to /var/folders/ph/gzh9clr1397fdk2m1013fhxc0000gn/T/_slackviewer/50ea6ff3ec9f9e745ead757609080e968c1c7706...
slack162018.zip extracted to /var/folders/ph/gzh9clr1397fdk2m1013fhxc0000gn/T/_slackviewer/50ea6ff3ec9f9e745ead757609080e968c1c7706
Traceback (most recent call last):
  File "/usr/local/bin/slack-export-viewer", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/slackviewer/main.py", line 50, in main
    configure_app(app, archive, debug)
  File "/Library/Python/2.7/site-packages/slackviewer/main.py", line 19, in configure_app
    reader = Reader(path)
  File "/Library/Python/2.7/site-packages/slackviewer/reader.py", line 16, in __init__
    with io.open(os.path.join(self._PATH, "users.json"), encoding="utf8") as f:
IOError: [Errno 2] No such file or directory: '/var/folders/ph/gzh9clr1397fdk2m1013fhxc0000gn/T/_slackviewer/50ea6ff3ec9f9e745ead757609080e968c1c7706/users.json'

**Comment by hfaran** [comment]
I just published v0.7.0 - can you update your version and try again and see if this is still happening?
