### ISSUE TITLE
500 Internal Server Error / TypeError

### ISSUE THREAD

**Issue by jlgore** [hfaran/slack-export-viewer#72]
Hello, I am attempting to use this on a Mac. I get a ```TypeError: '<' not supported between instances of 'dict' and 'dict'```

Not sure if I'm doing something wrong, but here's my output:

```slack-export-viewer -z ~/git/export.zip
/Users/obels/git/export.zip extracting to /var/folders/js/27tl2yc17wdfrh3_mb1647zc0000gp/T/_slackviewer/512eebdb2f56e8d873381d389a80e5258d264634...
/Users/obels/git/export.zip extracted to /var/folders/js/27tl2yc17wdfrh3_mb1647zc0000gp/T/_slackviewer/512eebdb2f56e8d873381d389a80e5258d264634.
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [09/Jul/2018 15:33:50] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/obels/anaconda/lib/python3.6/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/Users/obels/anaconda/lib/python3.6/site-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/Users/obels/anaconda/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/obels/anaconda/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/obels/anaconda/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/obels/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/obels/anaconda/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/obels/anaconda/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/obels/anaconda/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/obels/anaconda/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/obels/anaconda/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/obels/anaconda/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/obels/anaconda/lib/python3.6/site-packages/slackviewer/app.py", line 79, in index
    return channel_name("general")
  File "/Users/obels/anaconda/lib/python3.6/site-packages/slackviewer/app.py", line 23, in channel_name
    dm_users=sorted(dm_users),
TypeError: '<' not supported between instances of 'dict' and 'dict'```

**Comment by hfaran** [comment]
Can you try and see if this is still occurring with the latest release (0.7.0)?

**Comment by harshavardhana** [comment]
I see the following crashes with v1.0.4

```
    "pyshell"
  File "/usr/local/lib/python3.6/dist-packages/markdown2.py", line 184, in markdown
    use_file_vars=use_file_vars, cli=cli).convert(text)
  File "/usr/local/lib/python3.6/dist-packages/markdown2.py", line 377, in convert
    text = self._run_block_gamut(text)
  File "/usr/local/lib/python3.6/dist-packages/markdown2.py", line 1027, in _run_block_gamut
    text = self._form_paragraphs(text)
  File "/usr/local/lib/python3.6/dist-packages/markdown2.py", line 2162, in _form_paragraphs
    assert cuddled_list.startswith("<ul>") or cuddled_list.startswith("<ol>")
AssertionError
```
