### ISSUE TITLE
Browser not opening

### ISSUE THREAD

**Issue by TomRoark** [hfaran/slack-export-viewer#80]
Hiya, I'm unable to get to the browser pop stage of the program, seeing the following:

admin$ slack-export-viewer -z slack_exp.zip
slack_exp.zip extracting to /var/folders/pw/9pswtvxj7214t6pjf5zdk3bc0000gn/T/_slackviewer/9e5361f4333a34ad9e8ca7a2fb08ec378a2bf40e...
slack_exp.zip extracted to /var/folders/pw/9pswtvxj7214t6pjf5zdk3bc0000gn/T/_slackviewer/9e5361f4333a34ad9e8ca7a2fb08ec378a2bf40e
Traceback (most recent call last):
  File "/usr/local/bin/slack-export-viewer", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/slackviewer/main.py", line 50, in main
    configure_app(app, archive, debug)
  File "/Library/Python/2.7/site-packages/slackviewer/main.py", line 22, in configure_app
    top.channels = reader.compile_channels()
  File "/Library/Python/2.7/site-packages/slackviewer/reader.py", line 31, in compile_channels
    return self._create_messages(channel_names, channel_data)
  File "/Library/Python/2.7/site-packages/slackviewer/reader.py", line 154, in _create_messages
    day_messages = json.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 184 column 2 - line 219 column 2 (char 5446 - 6376)

**Comment by undaunt** [comment]
Seeing the same thing today. MacOS
