### ISSUE TITLE
Exporting direct messages using Fount export app

### ISSUE THREAD

**Issue by alsrealbad** [hfaran/slack-export-viewer#95]
I'm trying to export a direct message chain retrieved using Fount's export app:
http://export.fountstudio.com/web/install 

The app will produce a .json file, but the output file is not zipped. I've zipped the file and run slack-export-viewer and get the error message below. Will Fount's export app work with slack-export-viewer or am I experiencing other issues?

Error:
(venv) al@Altop ~ $ slack-export-viewer -z /home/al/downloads/slack-export-directmessage-2019-02-12T2321Z.json.zip
Traceback (most recent call last):
  File "/home/al/.local/bin/slack-export-viewer", line 9, in <module>
    load_entry_point('slack-export-viewer==0.8.2', 'console_scripts', 'slack-export-viewer')()
  File "/home/al/.local/venvs/slack-export-viewer/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/al/.local/venvs/slack-export-viewer/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/al/.local/venvs/slack-export-viewer/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/al/.local/venvs/slack-export-viewer/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/al/.local/venvs/slack-export-viewer/local/lib/python2.7/site-packages/slackviewer/main.py", line 50, in main
    configure_app(app, archive, debug)
  File "/home/al/.local/venvs/slack-export-viewer/local/lib/python2.7/site-packages/slackviewer/main.py", line 18, in configure_app
    path = extract_archive(archive)
  File "/home/al/.local/venvs/slack-export-viewer/local/lib/python2.7/site-packages/slackviewer/archive.py", line 55, in extract_archive
    raise TypeError("{} is not a zipfile".format(filepath))
TypeError: /home/al/downloads/slack-export-directmessage-2019-02-12T2321Z.json.zip is not a zipfile

**Comment by hfaran** [comment]
Currently only the standard export format from Slack is supported. I've never used Fount so I don't know what format this is in. Feel free to propose or submit a PR for supporting this format if you think it would be useful.

**Comment by Deilan** [comment]
That would be very nice to have!
